- name: Install Docker
  hosts: vagrant
  roles:
    - role: angstwad.docker_ubuntu
      ssh_port: 2222
      kernel_pkg_state: present

- name: Add the user with a bash shell, add him to the group 'docker' and set the authorized key
  hosts: vagrant
  tasks:
  - user:
      name: "{{ username }}"
      shell: /bin/bash
      groups: docker
      append: yes

  - name: Set authorized key taken from the file
    authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# NOTE: Should it be a part of the interested parties? e.g. traefik & services
- name: Create a network
  hosts: vagrant
  tasks:
  - docker_network:
      name: proxy
